unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on
set -g status off
set -ag terminal-overrides ",xterm-256color:RGB"
set  -g default-terminal "tmux-256color"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key i select-pane -U
bind-key l select-pane -R
